apiVersion: v1
kind: Service
metadata:
  name: supperdotnetapi-service
spec:
  selector:
    app: supperdotnetapi
  ports:
    - protocol: TCP
      port: 8040
      targetPort: 8040
  type: LoadBalancer  # Use ClusterIP if you don't need an external IP
